main/urls.py
from django.urls import path
from main.views import *


app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('login/', login_user, name='show_login'),
    path('register/', show_register, name='show_register'),
    #path('register/admin/', register_admin, name='r_admin'),
    #path('register/child/', register_child, name='r_child'),
    #path('register/caregiver/', register_caregiver, name='r_caregiver'),
    #path('register/driver/', register_driver, name='r_driver'),
    path('register/admin/', register_admin, name='r_admin'),
    path('register/child/', register_child, name='r_child'),
    path('register/caregiver/', register_caregiver, name='r_caregiver'),
    path('register/driver/', register_driver, name='r_driver'),
    path('main/',User_Dash,name='User_Dash'),
    path('Admin/',Admin_Dash,name='Admin_Dash'),
    path('Daily-Report/<str:name>',DailyRep_Page,name='DailyRep_Page'),
    path('Program/',Program_Page,name='Program_Page'), #this
    path('Enrollment/',Enrollment_Page,name='Enrollment_Page'),
    #####
    path('extracurricular/', extracurricular_page, name='extracurricular_page'),
    path('extracurricular/add', extra_add, name='extra_add'),
    path('extracurricular/edit/<str:ex_id>/', extra_edit, name='extra_edit'),
    path('extracurricular/detail/<str:ex_id>/', extra_details, name='extra_details'),
    path('extracurricular/delete/<str:ex_id>/', extra_delete, name='extra_delete'),
    
    path('menu/', menu_page, name='menu_page'),
    path('menu/add', menu_add, name='menu_add'),
    path('menu/edit/<str:menu_id>/', menu_edit, name='menu_edit'),
    path('menu/delete/<str:menu_id>/', menu_delete, name='menu_delete'),

    path('payment-history-admin/', pay_history_admin, name='pay_history_admin'),
    #####
    path('main/payment-history/', pay_history_user, name='pay_history_user'),
    path('main/pay-form', payform, name='payform'),
    path('menu/', menu_page, name='menu_page'),
    path('pickupschedule/', pickup_schedule_page, name='pickup_schedule_page'),
    path('child_list/', Child_List, name='children_page'),
    path('Activity/', Activity_Page, name='Act_Page'),
    path('Activity/delete/<str:activityid>/', Activity_Delete, name='Activity_Delete'),
    path('Act-Form/', Activity_Form, name="Act_Form"),
    path('Edit-Act/<str:activity_id>/', Edit_Activity, name="Edit_Act"),
    path('Menu-List/',Admin_Menu,name="Admin_Menu"),
    path('Menu-Form/',Add_Menu,name="Menu_Form"),
    path('Edit-Menu/',Edit_Menu,name="Edit_Menu"),
    path('Offered-Programs/',Offered_Program,name="Offered_Program"),
    path('Offer-New/<int:year>/',Offer,name="New_Offer"),
    path('Details/<int:year>/<str:name>',Prog_Detail,name="Prog_Details"),
    path('Add-ActivitySchedule/<int:year>/<str:name>',New_ActSched,name="New_ActSched"),
    path('Add-MenuSchedule/<int:year>/<str:name>',New_MenuSched,name="New_MenuSched"),
    path('Class/', Class_Page, name='Class_Page'),
    path('ChildreninClassPage/<str:class_name>/<str:year>/<str:program_id>/', Children_in_Class_Page, name='Children_In_Class_Page'),
    path('ChildrenDailyReport/<str:name>/<str:year>/<str:class_name>/<str:program_id>/', Children_Daily_Report, name="ChildrenDailyReport"),
    path('staff_list/',StaffList,name="Staff_List"),
    path('Daily-Report-Form/<str:name>/<str:year>/<str:class_name>/<str:program_id>/', DailyRepForm_Page, name='DailyRepForm_Page'),
    path('Room-List/', Admin_Room, name="Admin_Room"),
    path('Admin-Room-Form', Admin_Room_Form, name='Admin_Room_Form'),
    path('userPageRender/', userPageRender, name='userPageRender'),
    path('Shuttle-Service-Form/', ShuttleServiceForm, name='Shuttle_Service_Form'),
    path('program-page/', ProgramPage, name="program_page"),
    path('program-form-page/', ProgramFormPage, name="Admin_Program_Form"),
    path('program-edit/', ProgramPageEdit, name="program_edit"),
    path('delete_program/<int:year>/<str:name>/', Delete_Program, name='delete_program'),
    path('Extra-List/',ChildExtra,name="ChildExtra"), #this
    path('register/program',register_program,name = 'r_program'),
    path('register/activity/<int:year>/<str:name>', register_activity, name = 'r_activity'),
    path('register/menu/<int:year>/<str:name>', register_menu, name='r_menu'),
    path('logout/', logout_view, name='logout'),
    path('room/delete/<int:no>/<str:area>',room_delete,name='room_del'),
    path('register/room',register_room, name = 'r_rooms'),
    path('regis/prog', programpages, name="Ppages" ),
    path('Delete/prog<str:name>', programpagedelete, name="Dpages"),
    path('editprog/form/<str:name>',progeditpage,name='prg_edit')

]

simibiday/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/forms.py
from django.forms import ModelForm
from main.models import *
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import AbstractUser

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from main.forms import *
from main.models import *
from main.models import User
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
import json
from django.http import JsonResponse
import psycopg2
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import IntegrityError
from django.db import DatabaseError
import psycopg2
from psycopg2 import errors
from datetime import datetime
#from main.forms import * 
def show_main(request):
    context = {
        'name': 'Pak Bepe',
        'class': 'PBP A'
    }
    DB_NAME = 'railway'
    DB_USER = 'postgres'
    DB_PASS = 'C1CfFB-c5fb4feA3eE3FbdECe**-6d36'
    DB_HOST = 'monorail.proxy.rlwy.net'
    DB_PORT = '13998'
    conn = psycopg2.connect(database=DB_NAME,
                        user=DB_USER,
                        password=DB_PASS,
                        host=DB_HOST,
                        port=DB_PORT)

    cur = conn.cursor()
    cur.execute("""SET SEARCH_PATH TO MERAHBIRUDAYCARE;
    SELECT * FROM USERS;""")
    data = cur.fetchall()
    cur.close()
    cur = conn.cursor()
    cur.execute("""SELECT * FROM STAFF""")
    data2 = cur.fetchall()
    print(data)
    print(data2)
    cur.close()
    cur = conn.cursor()
    cur.execute("""SELECT * FROM DRIVER_DAY""")
    data3 = cur.fetchall()
    print(data3)
    cur.close()
    cur = conn.cursor()
    cur.execute("""SELECT * FROM CLASS""")
    data4 = cur.fetchall()
    print(data4)
    cur.close()
    conn.close()

# commit the changes
    
# # executing queries to create table


#  commit the changes
    #conn.commit()
    #print("Task finished successfully")
    #cur.close()
    #conn.close()

    return render(request, 'main.html', context)
@csrf_exempt
def show_login(request):
    context = {
        'name': 'Pak Bepe',
        'class': 'PBP A'
    }

    return render(request, 'login.html', context)

def show_register(request):
    context = {
        'name': 'Pak Bepe',
        'class': 'PBP A'
    }

    return render(request, 'register.html', context)

def register_admin_temp(request):
    context = {
        'name': 'Pak Bepe',
        'class': 'PBP A'
    }

    return render(request, 'r_admin.html', context)

def register_child_temp(request):
    context = {
        'name': 'Pak Bepe',
        'class': 'PBP A'
    }

    return render(request, 'r_child.html', context)

def register_caregiver_temp(request):
    context = {
        'name': 'Pak Bepe',
        'class': 'PBP A'
    }

    return render(request, 'r_caregiver.html', context)

def register_driver_temp(request):
    context = {
        'name': 'Pak Bepe',
        'class': 'PBP A'
    }

    return render(request, 'r_driver.html', context)


def User_Dash(request):
    context = {
        'name': 'Pak Bepe',
        'class': 'PBP A'
    }

    return render(request, 'UserPage.html', context)

def Admin_Dash(request):
    context = {
        'name': 'Pak Bepe',
        'class': 'PBP A'
    }

    return render(request, 'AdminPage.html', context)

def DailyRep_Page(request, name):

    DB_NAME = 'railway'
    DB_USER = 'postgres'
    DB_PASS = 'C1CfFB-c5fb4feA3eE3FbdECe**-6d36'
    DB_HOST = 'monorail.proxy.rlwy.net'
    DB_PORT = '13998'
    conn = psycopg2.connect(database=DB_NAME,
                        user=DB_USER,
                        password=DB_PASS,
                        host=DB_HOST,
                        port=DB_PORT)
    cur = conn.cursor()
    cur.execute(rf"""
                set search_path to merahbirudaycare;
                SELECT *
                FROM DAILY_REPORT DR
                join users u on u.userid = DR.userid
                WHERE CONCAT(u.first_name, ' ', u.last_name) = %s;
                """,[name])

    data =  cur.fetchall()
    print(data)
    conn.commit()
    context = {
        'name': 'Pak Bepe',
        'class': 'PBP A',
        'data': data,
    }
    cur.close()
    conn.close()

    return render(request, 'DailyReport.html', context)

def Program_Page(request):
    phone = request.user.phone_number
    DB_NAME = 'railway'
    DB_USER = 'postgres'
    DB_PASS = 'C1CfFB-c5fb4feA3eE3FbdECe**-6d36'
    DB_HOST = 'monorail.proxy.rlwy.net'
    DB_PORT = '13998'
    conn = psycopg2.connect(database=DB_NAME,
                    user=DB_USER,
                    password=DB_PASS,
                    host=DB_HOST,
                    port=DB_PORT)
    cur = conn.cursor()
    cur.execute("""SET SEARCH_PATH TO MERAHBIRUDAYCARE;
        SELECT userid
        FROM users
        WHERE phone_number=%s;
    """, [phone])
    userid =  cur.fetchone()
    print(userid[0])

    cur.execute(rf"""
        set search_path to merahbirudaycare;
        SELECT
            c.userid AS child_id,
            p.name AS program_name,
            e.year AS program_year,
            e.class AS class_name,
            CONCAT(u.first_name, ' ', u.last_name) AS caregiver,
            e.pickup_hour AS shuttle_pickup_hour,
            d.driver_license_number AS driver_phone_number,
            e.date AS enrolled_on_date,
            et.extracurriculars_taken,
            ms.activity_schedule,
            mns.menu_schedule
        FROM
            enrollment e
        JOIN
            child c ON e.userid = c.userid
        JOIN
            program p ON e.programid = p.programid
        JOIN
            users u ON u.userid = c.userid
        LEFT JOIN
            caregiver cg ON cg.userid = u.userid
        LEFT JOIN
            driver d ON e.driverid = d.userid
        LEFT JOIN (
            SELECT
                userid,
                programid,
                year,
                class,
                STRING_AGG(ex.name, ', ') AS extracurriculars_taken
            FROM
                extracurricular_taking et
            JOIN
                extracurricular ex ON et.extracurricularid = ex.extracurricularid
            GROUP BY
                userid, programid, year, class
        ) et ON et.userid = e.userid AND et.programid = e.programid AND et.year = e.year AND et.class = e.class
        LEFT JOIN (
            SELECT
                programid,
                year,
                day,
                STRING_AGG(name, ', ') AS activity_schedule
            FROM
                activity_schedule
            JOIN
                activity a ON activity_schedule.activity_id = a.id
            GROUP BY
                programid, year, day
        ) ms ON ms.programid = p.programid AND ms.year = e.year
        LEFT JOIN (
            SELECT
                programid,
                year,
                day,
                hour,
                STRING_AGG(m.name, ', ') AS menu_schedule
            FROM
                menu_schedule
            JOIN
                menu m ON menu_schedule.menuid = m.id
            GROUP BY
                programid, year, day, hour
        ) mns ON mns.programid = e.programid AND mns.year = e.year
        WHERE
            e.userid = %s;
    """, [userid[0]])

    data = cur.fetchall()

    context = {
        'program_data': data,
    }

    cur.close()
    conn.close()

    return render(request, 'Program.html', context)

def Enrollment_Page(request):
    context = {
        'name': 'Pak Bepe',
        'class': 'PBP A'
    }

    return render(request, 'Enrollment.html', context)

def extracurricular_page(request):
    DB_NAME = 'railway'
    DB_USER = 'postgres'
    DB_PASS = 'C1CfFB-c5fb4feA3eE3FbdECe**-6d36'
    DB_HOST = 'monorail.proxy.rlwy.net'
    DB_PORT = '13998'
    conn = psycopg2.connect(database=DB_NAME,
                        user=DB_USER,
                        password=DB_PASS,
                        host=DB_HOST,
                        port=DB_PORT)

    cur = conn.cursor()
    cur.execute(rf"""
                set search_path to merahbirudaycare;
                SELECT name, day, hour, extracurricularid
                FROM extracurricular;   
                """)

    data =  cur.fetchall()

    cur.execute(rf"""
                select distinct extracurricularid from extracurricular_taking;
                """)

    participant =  cur.fetchall()
    p_list = [item[0] for item in participant]
    context = {
        'data': data,
        'p_list' : p_list
    }
    cur.close()
    conn.close()
    return render(request, 'extracurricular.html', context)

@csrf_exempt
def extra_add(request):
    if request.method == "POST":
        exname = request.POST.get('exname')
        day = request.POST.get('day')
        hour = request.POST.get('hour')
        ex_uuid = str(uuid.uuid4())
        
        DB_NAME = 'railway'
        DB_USER = 'postgres'
        DB_PASS = 'C1CfFB-c5fb4feA3eE3FbdECe**-6d36'
        DB_HOST = 'monorail.proxy.rlwy.net'
        DB_PORT = '13998'
        conn = psycopg2.connect(database=DB_NAME,
                        user=DB_USER,
                        password=DB_PASS,
                        host=DB_HOST,
                        port=DB_PORT)
        cur = conn.cursor()
        cur.execute("""SET SEARCH_PATH TO MERAHBIRUDAYCARE;
            INSERT INTO EXTRACURRICULAR VALUES (%s, %s, %s, %s) 
        """, [ex_uuid, exname, day, hour])
        
        conn.commit()
        cur.close()
        conn.close()

        return redirect('main:extracurricular_page')
    return render(request, 'extraAdd.html')

def extra_details(request, ex_id):
    DB_NAME = 'railway'
    DB_USER = 'postgres'
    DB_PASS = 'C1CfFB-c5fb4feA3eE3FbdECe**-6d36'
    DB_HOST = 'monorail.proxy.rlwy.net'
    DB_PORT = '13998'

main/templates/ActivityForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand d-flex mx-auto justify-content-center">Activity Form</a>
    </nav>
    <br>    
<form method="post">
    <label for="Activity_Name: ">Activity Name: </label>
    <input type="text" id="Activity_Name" name="Activity_Name"><br>
    <br>
    <input type="submit" value="Add">
</form> 
</body>
</html>

main/templates/ClassListPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }
        #back a button {
            position: absolute;
            left: 50%;
            transform: translateX(-50%);

        }
        .row1 {
            background-color:aqua;
        }
    </style>
</head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand d-flex mx-auto justify-content-center">CLASS</a>
        </nav>
    </body>
<table>
    <thead>
        <tr>
            <th>Class Name</th>
            <th>Year</th>
            <th>Room No.</th>
            <th>Children List</th>
        </tr>
    </thead>
    <tbody>
        {% for row_data in row %}
        <tr>
            {% for data in row_data %}
            <td class="row1">{{ data }}</td>
            <td><a href="{% url 'main:Children_In_Class_Page' class_name=data.0 year=data.1 program_id=program_id%}"><button>[Children]</button></a></td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>
<div id="back">
        <a href="{% url 'main:User_Dash' %}"><button>Back</button></a></div>

</html>

main/templates/Enrollment.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <style>
            table {
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
            }
    
            th, td {
                border: 1px solid #dddddd;
                text-align: left;
                padding: 8px;
            }
    
            th {
                background-color: #f2f2f2;
            }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand d-flex mx-auto justify-content-center">Class Enrollment</a>
        </nav>
        <h5>Available Class: 
        </h5>
        <br>
        <table>
            <thead>
                <tr>
                    <th>Class</th>
                    <th>Caregiver</th>
                    <th>Room Name</th>
                    <th>Total Participant</th>
                    <th>Enroll</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Kindergarten-A</td>
                    <td>Ms. Hayley</td>
                    <td>Orchid</td>
                    <td>16/20</td>
                    <td><a href="{% url 'main:Shuttle_Service_Form' %}">Enroll</a></td>
                </tr>
                <tr>
                    <td>Kindergarten-B</td>
                    <td>Ms. Maxwell</td>
                    <td>Sunflower</td>
                    <td>20/20</td>
                    <td><a href="{% url 'main:Shuttle_Service_Form' %}">Enroll</a></td>
                </tr>
                <!-- Add more rows as needed -->
            </tbody>
        </table>
        <br>
        <div style="text-align: center;">
        <a href="{% url 'main:User_Dash' %}">
        <button>Back</button>
        </a>
    </div>

    </body>
   <h6></h6>



<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</html>

main/templates/PaymentHistoryChild.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand d-flex mx-auto justify-content-center">PAYMENT HISTORY</a>
    </nav>
    <br>    
<table>
    <thead>
        <tr>
            <th>Program Name</th>
            <th>Year</th>
            <th>Class</th>
            <th>Payment Date</th>
            <th>Type</th>
            <th>Fine</th>
            <th>Amount</th>
        </tr>
    </thead>
    <tbody>
        {% for row in data %}
        <tr>
            <td>{{ row.0 }}</td>
            <td>{{ row.1 }}</td>
            <td>{{ row.2 }}</td>
            <td>{{ row.3 }}</td>
            <td>{{ row.4 }}</td>
            <td>{{ row.5 }}</td>
            <td>{{ row.6 }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<br>
<div style="text-align: center;">
    <a href="{% url 'main:userPageRender' %}">
    <button>Back</button>
    </a>
</div>

</body>
</html>

main/templates/ProgramPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand d-flex mx-auto justify-content-center">Program</a>
    </nav>
    <br>    
<a href="{% url 'main:Ppages'%}">Add New Program</a>
<table>
    <thead>
        <tr>
            <th>Program Name</th>
            <th>Minimum Age</th>
            <th>Maximum Age</th>
            <th>Operation</th>
        </tr>
    </thead>
    <tbody>
        {% for row in data %}
        <tr>
            <td>{{ row.1 }}</td>
            <td>{{ row.2 }}</td>
            <td>{{ row.3 }}</td>
            <td><a href="{% url 'main:prg_edit' name=row.1 %}">Edit</a> / <a href="{% url 'main:Dpages' name=row.1 %}">Delete</a></td>
        </tr>
        {% endfor %}
        <!-- Add more rows as needed -->
    </tbody>
</table>
<br>
<div style="text-align: center;">
    <a href="{% url 'main:Admin_Dash' %}">
    <button>Back</button>
    </a>
</div>

</body>
</html>

main/templates/extracurricular.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand d-flex mx-auto justify-content-center">EXTRACURRICULAR</a>
    </nav>
    <br>  
    <div style="text-align: center;">
        <a href="{% url 'main:extra_add' %}">
        <button>Add New Extracurricular</button>
        </a>
    </div>  
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Day</th>
            <th>Hour</th>
            <th>Operation</th>
        </tr>
    </thead>
    <tbody>
        {% for row in data %}
        <tr>
            <td>{{ row.0 }}</td>
            <td>{{ row.1 }}</td>
            <td>{{ row.2 }}</td>
            <td><a href="{% url 'main:extra_details' row.3 %}">Detail</a> {% if row.3 not in p_list %} / <a href="{% url 'main:extra_edit' row.3 %}">Edit</a> / <a href="{% url 'main:extra_delete' row.3 %}">Delete</a> {% endif %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{{ participant }}
<br>
<div style="text-align: center;">
    <a href="{% url 'main:Admin_Dash' %}">
    <button>Back</button>
    </a>
</div>

</body>
</html>

main/templates/login.html
<form action="{% url 'main:show_login' %}" method="POST">
    {% csrf_token %}
    <label for="phone_number">Phone number:</label>
    <input type="phone_number" id="phone_number" name="phone_number"><br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password"><br><br>
    <a href="{% url 'main:User_Dash' %}">
        <button type="submit">Login</button>
    </a>
    <p>{{ error_message }}</p>
</form> 

main/templates/main.html
<h1>SIMBIDAY - DB23KI01</h1>

<a href="{% url 'main:show_login' %}">
    <button class="btn btn-danger me-2" type="button">Login</button>
</a>

<a href="{% url 'main:show_register' %}">
    <button class="btn btn-danger me-2" type="button">Register</button>
</a>

main/templates/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand d-flex mx-auto justify-content-center">MENU</a>
    </nav>
    <br>  
    <div style="text-align: center;">
        <a href="{% url 'main:menu_add' %}">
        <button>Add New Menu</button>
        </a>
    </div>  
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Operation</th>
        </tr>
    </thead>
    <tbody>
        {% for row in data %}
        <tr>
            <td>{{ row.0 }}</td>
            <td>{{ row.1 }}</td>
            <td>{% if row.2 not in ip_list %}<a href="{% url 'main:menu_edit' row.2 %}">Edit</a> / <a href="{% url 'main:menu_delete' row.2 %}">Delete</a> {% endif %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{{ participant }}
<br>
<div style="text-align: center;">
    <a href="{% url 'main:Admin_Dash' %}">
    <button>Back</button>
    </a>
</div>

</body>
</html>

main/templates/register.html
<h1>SIMBIDAY - DB23KI01</h1>

<a href="{% url 'main:r_admin' %}">
    <button class="btn btn-danger me-2" type="button">ADMIN</button>
</a>
<br>
<a href="{% url 'main:r_child' %}">
    <button class="btn btn-danger me-2" type="button">CHILD</button>
</a>
<br>
<a href="{% url 'main:r_caregiver' %}">
    <button class="btn btn-danger me-2" type="button">CAREGIVER</button>
</a>
<br>
<a href="{% url 'main:r_driver' %}">
    <button class="btn btn-danger me-2" type="button">DRIVER</button>
</a>